"""initial_schema

Tables (autogenerated), then the security layer Alembic cannot see: extensions,
enum types, the auth.users foreign key, RLS policies, and the signup trigger.

Revision ID: b08551e6b4f6
Revises:
Created: 2026-08-06 00:50:20
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b08551e6b4f6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# SECURITY DEFINER is load-bearing, not a convenience: a policy on memberships
# that queried memberships directly would recurse infinitely. Running inside a
# definer function bypasses RLS and breaks the cycle. search_path is pinned on
# every one, because a mutable search_path on a definer function is a
# privilege-escalation vector.
HELPERS = """
create or replace function public.current_user_id()
returns uuid language sql stable security definer
set search_path = public, pg_temp as $$
  select id from public.users where auth_user_id = auth.uid();
$$;

create or replace function public.is_org_member(target_org uuid)
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.memberships m
    where m.org_id = target_org and m.user_id = public.current_user_id()
  );
$$;

create or replace function public.has_org_role(target_org uuid, allowed public.org_role[])
returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (
    select 1 from public.memberships m
    where m.org_id = target_org
      and m.user_id = public.current_user_id()
      and m.role = any(allowed)
  );
$$;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
"""


# Domains where the email domain names the mail provider rather than the company.
NAMING_HELPERS = """
create or replace function public.is_free_email_domain(domain text)
returns boolean language sql immutable as $$
  select lower(domain) = any (array[
    'gmail.com','googlemail.com','yahoo.com','yahoo.co.in','yahoo.co.uk',
    'outlook.com','hotmail.com','hotmail.co.uk','live.com','msn.com',
    'icloud.com','me.com','mac.com','aol.com','proton.me','protonmail.com',
    'pm.me','zoho.com','zohomail.com','gmx.com','gmx.de','yandex.com',
    'mail.com','rediffmail.com','fastmail.com','tutanota.com','duck.com','hey.com'
  ]);
$$;

create or replace function public.slugify(value text)
returns text language sql immutable as $$
  select coalesce(
    nullif(trim(both '-' from regexp_replace(lower(value), '[^a-z0-9]+', '-', 'g')), ''),
    'org'
  );
$$;
"""


POLICIES = """
alter table public.users         enable row level security;
alter table public.users         force  row level security;
alter table public.organisations enable row level security;
alter table public.organisations force  row level security;
alter table public.memberships   enable row level security;
alter table public.memberships   force  row level security;
alter table public.suppressions  enable row level security;
alter table public.suppressions  force  row level security;

create policy users_select on public.users for select using (
  id = public.current_user_id()
  or exists (
    select 1 from public.memberships mine
    join public.memberships theirs on theirs.org_id = mine.org_id
    where mine.user_id = public.current_user_id()
      and theirs.user_id = public.users.id
  )
);
create policy users_update_self on public.users for update
  using (id = public.current_user_id())
  with check (id = public.current_user_id());

create policy organisations_select on public.organisations for select
  using (public.is_org_member(id));
create policy organisations_update on public.organisations for update
  using (public.has_org_role(id, array['owner','admin']::public.org_role[]))
  with check (public.has_org_role(id, array['owner','admin']::public.org_role[]));
create policy organisations_insert on public.organisations for insert
  with check (public.current_user_id() is not null);

create policy memberships_select on public.memberships for select
  using (public.is_org_member(org_id));
create policy memberships_insert on public.memberships for insert
  with check (public.has_org_role(org_id, array['owner','admin']::public.org_role[]));
create policy memberships_update on public.memberships for update
  using (public.has_org_role(org_id, array['owner','admin']::public.org_role[]))
  with check (public.has_org_role(org_id, array['owner','admin']::public.org_role[]));
create policy memberships_delete on public.memberships for delete using (
  user_id = public.current_user_id()
  or public.has_org_role(org_id, array['owner','admin']::public.org_role[])
);

create policy suppressions_select on public.suppressions for select
  using (public.is_org_member(org_id));
create policy suppressions_insert on public.suppressions for insert
  with check (public.has_org_role(
    org_id, array['owner','admin','operator']::public.org_role[]));
-- Removing one makes somebody who opted out callable again: owners only. There is
-- deliberately no UPDATE policy — a suppression is added or removed, never edited.
create policy suppressions_delete on public.suppressions for delete
  using (public.has_org_role(org_id, array['owner']::public.org_role[]));
"""


# The DELETE branch skips the check when the parent org or user is already gone.
# Postgres applies the parent delete before firing the referential action, so
# mid-cascade absence distinguishes "revoking a membership" from "cleaning up
# after a deleted owner". Without it no account could ever be deleted — see
# ISSUES.md #13.
LAST_OWNER_GUARD = """
create or replace function public.protect_last_owner()
returns trigger language plpgsql security definer
set search_path = public, pg_temp as $$
declare
  remaining_owners int;
  target_org uuid := coalesce(old.org_id, new.org_id);
begin
  if old.role <> 'owner' then
    return coalesce(new, old);
  end if;

  if tg_op = 'UPDATE' and new.role = 'owner' then
    return new;
  end if;

  if tg_op = 'DELETE' then
    if not exists (select 1 from public.organisations where id = old.org_id) then
      return old;
    end if;
    if not exists (select 1 from public.users where id = old.user_id) then
      return old;
    end if;
  end if;

  select count(*) into remaining_owners
  from public.memberships
  where org_id = target_org and role = 'owner' and user_id <> old.user_id;

  if remaining_owners = 0 then
    raise exception
      'This is the last owner of the organisation. Transfer ownership to someone else first.'
      using errcode = 'restrict_violation';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger memberships_protect_last_owner
  before update or delete on public.memberships
  for each row execute function public.protect_last_owner();
"""


# A trigger rather than application code: atomic with the auth row, and it fires
# for every signup path (password, Google, admin-created), so no user can exist
# without an organisation.
SIGNUP_TRIGGER = """
create or replace function public.handle_new_auth_user()
returns trigger language plpgsql security definer
set search_path = public, pg_temp as $$
declare
  new_user_id  uuid;
  new_org_id   uuid;
  display_name text;
  email_domain text;
  org_name     text;
  base_slug    text;
  final_slug   text;
  suffix       int := 1;
begin
  display_name := nullif(trim(coalesce(
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'name', '')), '');

  insert into public.users (auth_user_id, email, name, avatar_url)
  values (new.id, new.email, display_name,
          nullif(new.raw_user_meta_data ->> 'avatar_url', ''))
  on conflict (auth_user_id) do update set email = excluded.email
  returning id into new_user_id;

  if exists (select 1 from public.memberships where user_id = new_user_id) then
    return new;
  end if;

  email_domain := split_part(new.email, '@', 2);

  if email_domain is null or email_domain = ''
     or public.is_free_email_domain(email_domain) then
    org_name := coalesce(display_name, split_part(new.email, '@', 1)) || '''s workspace';
  else
    org_name := initcap(replace(split_part(email_domain, '.', 1), '-', ' '));
  end if;

  base_slug := public.slugify(org_name);
  final_slug := base_slug;
  while exists (select 1 from public.organisations where slug = final_slug) loop
    suffix := suffix + 1;
    final_slug := base_slug || '-' || suffix;
  end loop;

  insert into public.organisations (name, slug, country, timezone)
  values (org_name, final_slug, 'IN', 'Asia/Kolkata')
  returning id into new_org_id;

  insert into public.memberships (org_id, user_id, role)
  values (new_org_id, new_user_id, 'owner');

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_auth_user();
"""


# RLS decides which rows are visible; grants decide which tables are reachable at
# all. Both are required — RLS without a grant is unreadable, a grant without RLS
# leaks. `anon` gets nothing: every read here requires a signed-in user.
GRANTS = """
grant usage on schema public to authenticated, anon;
grant select, update                 on public.users         to authenticated;
grant select, insert, update         on public.organisations to authenticated;
grant select, insert, update, delete on public.memberships   to authenticated;
grant select, insert, delete         on public.suppressions  to authenticated;
"""


TOUCH_TRIGGERS = """
create trigger users_touch_updated_at before update on public.users
  for each row execute function public.touch_updated_at();
create trigger organisations_touch_updated_at before update on public.organisations
  for each row execute function public.touch_updated_at();
"""


def upgrade() -> None:
    # CITEXT and gen_random_uuid() must exist before any table uses them.
    op.execute("create extension if not exists citext")
    op.execute("create extension if not exists pgcrypto")

    # The models declare create_type=False, so the types are created once here.
    op.execute("create type public.org_role as enum ('owner','admin','operator','viewer')")
    op.execute(
        "create type public.suppression_source as enum ('opt_out','manual','imported','api')"
    )

    op.create_table(
        "organisations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", postgresql.CITEXT(), nullable=False),
        sa.Column("plan_id", sa.String(length=32), server_default="free", nullable=False),
        sa.Column(
            "credit_balance_paise", sa.BigInteger(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="Asia/Kolkata", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(name)) between 1 and 120", name="organisations_name_length"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        schema="public",
    )
    op.create_index(
        "organisations_active_idx",
        "organisations",
        ["id"],
        unique=False,
        schema="public",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("avatar_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("auth_user_id"),
        sa.UniqueConstraint("email"),
        schema="public",
    )

    # Raw DDL so the auth schema never enters Alembic's metadata, where a future
    # autogenerate could propose dropping it.
    op.execute(
        "alter table public.users add constraint users_auth_user_id_fkey "
        "foreign key (auth_user_id) references auth.users (id) on delete cascade"
    )

    op.create_table(
        "memberships",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(name="org_role", schema="public", create_type=False),
            server_default="operator",
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["public.users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["org_id"], ["public.organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["public.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("org_id", "user_id"),
        schema="public",
    )
    op.create_index(
        "memberships_user_idx", "memberships", ["user_id"], unique=False, schema="public"
    )

    op.create_table(
        "suppressions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("phone_hash", sa.String(length=64), nullable=False),
        sa.Column("phone_e164", sa.String(length=20), nullable=True),
        sa.Column(
            "source",
            postgresql.ENUM(name="suppression_source", schema="public", create_type=False),
            server_default="manual",
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("suppressed_by", sa.UUID(), nullable=True),
        sa.Column(
            "suppressed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("length(phone_hash) = 64", name="suppressions_hash_length"),
        sa.ForeignKeyConstraint(["org_id"], ["public.organisations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["suppressed_by"], ["public.users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "phone_hash", name="suppressions_org_phone_key"),
        schema="public",
    )
    op.create_index(
        "suppressions_org_recent_idx",
        "suppressions",
        ["org_id", sa.literal_column("suppressed_at DESC")],
        unique=False,
        schema="public",
    )

    op.execute(HELPERS)
    op.execute(NAMING_HELPERS)
    op.execute(POLICIES)
    op.execute(LAST_OWNER_GUARD)
    op.execute(SIGNUP_TRIGGER)
    op.execute(GRANTS)
    op.execute(TOUCH_TRIGGERS)


def downgrade() -> None:
    op.execute("drop trigger if exists on_auth_user_created on auth.users")
    op.execute("drop function if exists public.handle_new_auth_user() cascade")
    op.execute("drop function if exists public.protect_last_owner() cascade")
    op.execute("drop function if exists public.is_free_email_domain(text) cascade")
    op.execute("drop function if exists public.slugify(text) cascade")

    op.drop_index("suppressions_org_recent_idx", table_name="suppressions", schema="public")
    op.drop_table("suppressions", schema="public")
    op.drop_index("memberships_user_idx", table_name="memberships", schema="public")
    op.drop_table("memberships", schema="public")
    op.execute("alter table public.users drop constraint if exists users_auth_user_id_fkey")
    op.drop_table("users", schema="public")
    op.drop_index(
        "organisations_active_idx",
        table_name="organisations",
        schema="public",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("organisations", schema="public")

    # After the tables: has_org_role depends on the org_role type.
    op.execute("drop function if exists public.has_org_role(uuid, public.org_role[]) cascade")
    op.execute("drop function if exists public.is_org_member(uuid) cascade")
    op.execute("drop function if exists public.current_user_id() cascade")
    op.execute("drop function if exists public.touch_updated_at() cascade")
    op.execute("drop type if exists public.suppression_source")
    op.execute("drop type if exists public.org_role")
